import assert from 'node:assert/strict';
import fs from 'node:fs';
const calc=await import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync('src/lib/calc.js','utf8')).toString('base64'));
const moduleSource=fs.readFileSync('src/lib/assistantDrafts.js','utf8').replace("import {nextDocumentNumber} from './calc';",'const nextDocumentNumber = '+calc.nextDocumentNumber.toString()+';');
const {mergeAssistantDrafts}=await import('data:text/javascript;base64,'+Buffer.from(moduleSource).toString('base64'));
const base={activeBrandId:'jfe',brands:[{id:'jfe'},{id:'sauna'}],settings:{estimatePrefix:'EST',invoicePrefix:'INV',gstRate:.05,pstRate:.07},customers:[],jobs:[],documents:[],expenses:[]};
const row={id:'request-1',user_id:'owner',payload:{customer:{id:'jessie',name:'Jessie Marshall',email:''},job:{id:'deck',brandId:'jfe',name:'Small rear deck'},document:{id:'estimate-1',brandId:'jfe',type:'estimate',status:'draft',date:'2026-10-01',items:[{description:'Deck rebuild',qty:1,unitPrice:3300,taxCode:'EXEMPT'}]}}};
const next=mergeAssistantDrafts(base,[row],'owner');
assert.equal(base.documents.length,0);
assert.equal(next.documents[0].number,'EST-0001');
assert.equal(calc.documentTotals(next.documents[0],next.settings).total,3300);
assert.equal(next.documents[0].status,'draft');
assert.deepEqual(next.documents[0].payments,[]);
assert.equal(mergeAssistantDrafts(next,[row],'owner'),next);
const edited={...next,documents:[{...next.documents[0],title:'Edited',status:'accepted'}]};
assert.equal(mergeAssistantDrafts(edited,[row],'owner').documents[0].title,'Edited');
assert.throws(()=>mergeAssistantDrafts(next,[row],'other'),/account/);
assert.throws(()=>mergeAssistantDrafts(base,[{...row,user_id:'other'}],'owner'),/account/);
assert.throws(()=>mergeAssistantDrafts(base,[{...row,payload:{...row.payload,document:{...row.payload.document,status:'sent'}}}],'owner'),/draft/);
const existing={...base,customers:[{id:'existing',name:'Jessie Marshall',email:'kept@example.com'}],documents:[{id:'old',type:'estimate',number:'EST-0008',status:'draft'}]};
const merged=mergeAssistantDrafts(existing,[row],'owner');
assert.equal(merged.customers.length,1);
assert.equal(merged.documents[1].billTo.email,'kept@example.com');
assert.equal(merged.documents[1].number,'EST-0009');
assert.equal(merged.jobs[0].customerId,'existing');
assert.throws(()=>mergeAssistantDrafts({...existing,customers:[...existing.customers,{id:'duplicate',name:'Jessie Marshall'}]},[row],'owner'),/Multiple clients/);
const restarted={...next,assistantAppliedDraftIds:[]};
assert.equal(mergeAssistantDrafts(restarted,[row],'owner').documents.length,1);
console.log('PASS: draft delivery, CAD total, preserved edits/contact data, retries, numbering and account isolation');
