import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const load=async path=>import('data:text/javascript;base64,'+Buffer.from(await readFile(path,'utf8')).toString('base64'));
const {documentTotals,jobSummary}=await load('./src/lib/calc.js');
const {migratePrototype}=await load('./src/lib/migrate.js');
const {SEED}=await load('./src/data/seed.js');
const prototype={clients:[{name:'Test Client',email:'test@example.invalid'}],docs:[{id:'source-1',type:'invoice',number:'INV0042',business:'John Forsyth Enterprises',client:'Test Client',jobName:'Test job',date:'2026-10-01',gstRate:5,pstRate:7,items:[{desc:'Work',qty:2,rate:100,unit:'hours'}],payments:[{amount:50}],paymentPlan:[50,50],contacts:[{name:'Billing',email:'billing@example.invalid',primary:true}]}],expenses:[{id:'expense-1',business:'John Forsyth Enterprises',jobName:'Test job',amount:112,gst:5,pst:7}]};
const original=JSON.stringify(SEED),migrated=migratePrototype(prototype,SEED);
assert.equal(JSON.stringify(SEED),original,'import cannot mutate existing state');
assert.equal(migrated.documents.length,1);
assert.equal(migrated.expenses[0].netAmount,100);
assert.equal(migrated.documents[0].contacts[0].primary,true);
assert.deepEqual(migratePrototype(prototype,migrated),migrated,'reimport is idempotent');
const totals=documentTotals(migrated.documents[0],SEED.settings);
assert.equal(totals.total,224);assert.equal(totals.paid,50);assert.equal(totals.dueNow,62);assert.equal(totals.balance,174);
assert.equal(documentTotals({...migrated.documents[0],taxInclusive:true,items:[{qty:1,unitPrice:112,taxCode:'GST_PST'}]},SEED.settings).total,112);
assert.throws(()=>migratePrototype({...prototype,expenses:[{id:'bad',amount:4,gst:5}]},SEED));
const state={...migrated,documents:[{...migrated.documents[0],status:'sent'}, {...migrated.documents[0],id:'estimate',type:'estimate',status:'accepted'}]};
const profit=jobSummary(state,state.jobs[0].id);
assert.equal(profit.revenue,200,'accepted estimate must not double count invoice');assert.equal(profit.payments,50);assert.equal(profit.directCosts,112);assert.equal(profit.profit,-62);
console.log('PASS: import preserves records; repeat import; payment stages; inclusive tax; job profit.');
const {validateNativeBackup}=await load('./src/lib/migrate.js');
assert.equal(validateNativeBackup({...migrated,cloudBackupUserId:'previous-account'}).cloudBackupUserId,null);
assert.throws(()=>validateNativeBackup({...migrated,jobs:[{...migrated.jobs[0],customerId:'missing'}]}));
assert.throws(()=>validateNativeBackup({...migrated,documents:[{...migrated.documents[0],items:[{qty:'not-a-number',unitPrice:5}]}]}));
console.log('PASS: native restore rejects invalid records and disables account-specific automatic backup.');
const {nextDocumentNumber}=await load('./src/lib/calc.js');
assert.equal(nextDocumentNumber(migrated,'invoice'),'INV-0043');
const {accountantCsv}=await load('./src/lib/export.js');
const csv=accountantCsv({...migrated,customers:[{...migrated.customers[0],name:'=HYPERLINK("bad")'}]});
assert.ok(csv.includes("'=HYPERLINK"),'CSV neutralizes formula-like customer values');
assert.ok(csv.includes('"112","5","7"'));
const calcSource=await readFile('./src/lib/calc.js','utf8');
const pdfSource=(await readFile('./src/lib/pdf.js','utf8')).replace(/^import .*;\n/gm,'');
const {documentHtml}=await import('data:text/javascript;base64,'+Buffer.from(calcSource+'\n'+pdfSource).toString('base64'));
const html=documentHtml(migrated,{...migrated.documents[0],billTo:{name:'<script>bad</script>',email:'primary@example.invalid'},items:[{description:'Test',qty:1,unit:'hours',unitPrice:100,internalCost:7777,taxCode:'GST'}]});
assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('7777'));assert.ok(html.includes('billing@example.invalid'));assert.ok(html.includes('primary@example.invalid'));assert.ok(html.includes('Payment 1 due now'));assert.ok(html.includes('50% / 50%'));
const late=documentTotals({type:'invoice',items:[{qty:1,unitPrice:100,taxCode:'EXEMPT'}],payments:[],dueDate:'2026-01-01',lateFeeEnabled:true,lateFeeRate:2},SEED.settings,new Date('2026-02-02T12:00:00'));
assert.equal(late.lateFee,4);assert.equal(late.balance,104);
console.log('PASS: document numbering, CSV export, PDF recipients/privacy, and late-fee calculation.');
