const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');const {chromium}=require('playwright');
(async()=>{
 const root=path.resolve('dist-web');const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');const file=path.join(root,url.pathname==='/'?'index.html':decodeURIComponent(url.pathname));try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end()}});await new Promise(r=>server.listen(8766,'127.0.0.1',r));
 const b=await chromium.launch({...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu'],headless:true});
 try{const page=await b.newPage({viewport:{width:393,height:852},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8766');await page.getByText('+ New Invoice',{exact:true}).waitFor();await page.screenshot({path:'dist-web/home-review.png',fullPage:true});console.log((await page.locator('body').innerText()).slice(0,1000));await page.getByText('+ New Invoice',{exact:true}).click();await page.getByText('Primary email',{exact:true}).waitFor();await page.waitForFunction(()=>[...document.querySelectorAll('*')].some(e=>e.textContent==='Primary email'&&e.getBoundingClientRect().y>0&&e.getBoundingClientRect().y<700));await page.screenshot({path:'dist-web/invoice-review.png',fullPage:true,animations:'disabled'});console.log('Editor fields:',await page.locator('input').count());
await page.getByLabel('Job name',{exact:true}).fill('Test fence');await page.getByLabel('Client',{exact:true}).fill('Test Client');await page.getByLabel('Primary email',{exact:true}).fill('test@example.invalid');await page.getByLabel('Description',{exact:true}).fill('Fence labour');await page.getByLabel('Quantity',{exact:true}).fill('2');await page.getByLabel('Unit',{exact:true}).fill('hours');await page.getByLabel('Price per unit',{exact:true}).fill('100');await page.getByText('50/50',{exact:true}).click();await page.getByRole('button',{name:'Save draft',exact:true}).click();
await page.waitForFunction(()=>JSON.parse(localStorage.getItem('forsyth-business-v2')||'{}').documents?.length===1);await page.getByText('Invoices',{exact:true}).click();await page.getByText('Invoice INV-0001',{exact:true}).waitFor();await page.getByLabel('Payment received',{exact:true}).fill('50');await page.getByRole('button',{name:'Record payment',exact:true}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('forsyth-business-v2')||'{}').documents?.[0]?.payments?.[0]?.amount===50);await page.screenshot({path:'dist-web/saved-invoice-review.png',fullPage:true});
let state=await page.evaluate(()=>JSON.parse(localStorage.getItem('forsyth-business-v2')));assert.equal(state.customers[0].name,'Test Client');assert.equal(state.documents[0].items[0].unit,'hours');assert.equal(state.documents[0].status,'partial');assert.deepEqual(state.documents[0].paymentPlan,[50,50]);
await page.reload();await page.getByText('+ New Invoice',{exact:true}).waitFor();state=await page.evaluate(()=>JSON.parse(localStorage.getItem('forsyth-business-v2')));assert.equal(state.documents[0].payments[0].amount,50);assert.deepEqual(errors,[]);console.log('PASS: create client/job/invoice, payment plan, record payment, and reload persistence.');console.log('PASS: home and new-document screens load without runtime errors.');}
 finally{await b.close();server.close();}
})().catch(e=>{console.error(e);process.exit(1)});
